spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mytest
    password: Hades.1001
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5

server:
  port: 80

redis:
  host : 111.231.81.53
  port : 6379
  timeout : 3
  password :
  poolMaxTotal : 10
  poolMaxIdle : 10
  poolMaxWait : 3






